name: Automatic Merge
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Auto merge pull request
        uses: lots0logs/gh-action-auto-merge@1.0.0
        with:
          entryPoint: "/entrypoint.sh"
          args: "merge"
          run-as-root: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MERGE_METHOD: "merge"
